config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'gists#index'
  get '/gists' => 'gists#index', as: 'all_gists'
  get '/gists/:id' => 'gists#show', as: 'gist'

  get '/user/:name/gists' => 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
require 'date'

class GistsController < ApplicationController
	include GistsHelper

	def index
		gists = HTTParty.get(gists_host + "/gists/public?per_page=100", :verify => false).parsed_response
		@gists = format_gists(gists)
		@order = "asc"
		@orderfield = ""

		if params.has_key?(:orderfield) && params[:orderfield].to_s != ""
			@orderfield = params[:orderfield]

			if params.has_key?(:order) && params[:order].to_s == "desc"
				@order = "desc"
				@gists.sort! do |x,y| y[@orderfield].to_s.downcase  <=> x[@orderfield].to_s.downcase end
			else
				@gists.sort! do |x,y| x[@orderfield].to_s.downcase  <=> y[@orderfield].to_s.downcase end
			end
		end
	end

	def show
		@gist = gists = HTTParty.get(gists_host + "/gists/" + params[:id], :verify => false).parsed_response
	end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include GistsHelper
	def show
		@user = params["name"]
		gists = HTTParty.get(gists_host + get_user_gists_route(@user) + "?per_page=100", :verify => false).parsed_response
		@gists = format_gists(gists)
	end


	private
	def get_user_gists_route(name)
		return "/users/" + name + "/gists"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
	def gists_host
		"https://api.github.com"
	end

	def no_user_placeholder
		"anonymous"
	end

	def format_gists(gists)
		formated_gists = Array.new
		gists.each do |gist|
			formated_gists.push format_gist(gist)
		end
		return formated_gists
	end

	def format_gist(gist)
		formated_gist = Hash.new

		formated_gist["id"] = gist["id"]
		formated_gist["owner"] = gist["owner"].nil? ? no_user_placeholder : gist["owner"]["login"]
		formated_gist["description"] = gist["description"].to_s == '' ? "no description" : gist["description"]
		formated_gist["created_at"] = _format_date(gist["created_at"])
		formated_gist["updated_at"] = _format_date(gist["updated_at"])
		formated_gist["number_of_files"] = gist["files"].nil? ? "0" : gist["files"].length
		formated_gist["number_of_comments"] = gist["comments"].nil? ? "0" : gist["comments"]

		return formated_gist
	end

	def order_link(field)
		order_desc_check = @orderfield == field && @order == "asc"
		orderèpart = order_desc_check ?  "&order=desc" : ""
		return all_gists_path + "?orderfield=" + field + orderèpart
	end

	private
	def _format_date(datetime_string)
		DateTime.parse(datetime_string).strftime("%e %b %Y %T")
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gists/index.html.erb
<div class="main gists-index">
  <div class="container">
  	<table>
  		<thead>
  			<tr>
  				<th> <%= link_to "Owner", order_link("owner") %> </th>
  				<th> <%= link_to "Descripiton", order_link("description")%>  </th>
          <th> <%= link_to "Date of creation", order_link("created_at")%>  </th>
  				<th> <%= link_to "Last Update", order_link("updated_at")%>  </th>
  				<th> <%= link_to "Number of files", order_link("number_of_files") %> </th>  				
          <th> <%= link_to "Number of comments", order_link("number_of_comments") %>  </th>         
  				<th> &nbsp;</th>  				
  			</tr>
  		</thead>
  		<tbody>
  			<% @gists.each do |g| %>
		    	<tr>
            <td>
              <% if no_user_placeholder != g["owner"] %>
  		    		  <%= link_to g["owner"], user_path(:name=>g["owner"]) %>
              <% else %>
                <%= g["owner"] %>
              <% end %>
            </td>
		    		<td><%= g["description"] %></td>
            <td><%= g["created_at"] %></td>
		    		<td><%= g["updated_at"] %></td>
		    		<td><%= g["number_of_files"]  %></td>
            <td><%= g["number_of_comments"]  %></td>
		    		<td><%= link_to "See More", gist_path(:id=>g["id"]) %></td>
	    		</tr>
		    <% end %>
  		</tbody>
  	</table>
    

  </div>
</div>

app/views/gists/show.html.erb
<div class="main gists-index">
  <div class="container">
  	<h2> <%= @gist["description"] %> </h2>
  	<% if @gist["owner"].nil? %>
  		<p> the owner is anonymous </p>
	<% else %>
		<%= link_to @gist["owner"]["login"], user_path(:name=>@gist["owner"]["login"]) %>
	<% end %>
	
	<% if @gist["files"].nil? || @gist["files"].length == 0 %>
		<p>There is no files in this gists</p>
	<% else %>
		<table>
			<thead>
				<tr>
					<th>FileName</th>
					<th>Language</th>
					<th>Content</th>
				</tr>
			</thead>
			<tbody>
				<% @gist["files"].each do |file_name, f| %>
					<tr>
						<td><%= file_name %></td>
						<td><%= f["language"]%></td>
						<td><%= f["content"]%></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GistsApp</title>
    <%= csrf_meta_tags %>

   	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="main gists-index">
  <div class="container">
    <div class="header">
      <h2> Gists of <%= @user %></h2>
    </div>
  	<table>
  		<thead>
  			<tr>
  				<th> Descripiton </th>
          <th> Date of creation </th>
  				<th> Last Update </th>
  				<th> Number of files </th>  				
  				<th> Number of comments </th>  				
  			</tr>
  		</thead>
  		<tbody>
  			<% @gists.each do |g| %>
		    	<tr>
		    		<td><%= g["description"] %></td>
            <td><%= g["created_at"] %></td>
		    		<td><%= g["updated_at"] %></td>
		    		<td><%= g["number_of_files"]  %></td>
		    		<td><%= g["number_of_comments"]  %></td>
	    		</tr>
		    <% end %>
  		</tbody>
  	</table>
    

  </div>
</div>